-- 000007_rls_policies.down.sql
DROP POLICY IF EXISTS audit_ins ON audit_log;
DROP POLICY IF EXISTS audit_sel ON audit_log;
DROP POLICY IF EXISTS docs_all ON documents;
DROP POLICY IF EXISTS docs_sel ON documents;
DROP POLICY IF EXISTS transfers_sel ON transfers;
DROP POLICY IF EXISTS fintx_all ON financial_transactions;
DROP POLICY IF EXISTS fintx_sel ON financial_transactions;
DROP POLICY IF EXISTS fincat_all ON financial_categories;
DROP POLICY IF EXISTS fincat_sel ON financial_categories;
DROP POLICY IF EXISTS att_all ON group_attendance;
DROP POLICY IF EXISTS att_sel ON group_attendance;
DROP POLICY IF EXISTS groups_all ON small_groups;
DROP POLICY IF EXISTS groups_sel ON small_groups;
DROP POLICY IF EXISTS ministry_mem_all ON ministry_members;
DROP POLICY IF EXISTS ministry_mem_sel ON ministry_members;
DROP POLICY IF EXISTS ministries_all ON ministries;
DROP POLICY IF EXISTS ministries_sel ON ministries;
DROP POLICY IF EXISTS benefactors_all ON benefactors;
DROP POLICY IF EXISTS benefactors_sel ON benefactors;
DROP POLICY IF EXISTS visitors_all ON visitors;
DROP POLICY IF EXISTS guests_sel ON visitors;
DROP POLICY IF EXISTS rels_all ON member_relationships;
DROP POLICY IF EXISTS rels_sel ON member_relationships;
DROP POLICY IF EXISTS families_all ON families;
DROP POLICY IF EXISTS families_sel ON families;
DROP POLICY IF EXISTS members_all ON members;
DROP POLICY IF EXISTS members_sel ON members;
DROP POLICY IF EXISTS users_all ON users;
DROP POLICY IF EXISTS users_sel ON users;
DROP POLICY IF EXISTS roles_all ON roles;
DROP POLICY IF EXISTS roles_sel ON roles;
DROP POLICY IF EXISTS branch_all ON branches;
DROP POLICY IF EXISTS branch_sel ON branches;
DROP POLICY IF EXISTS tenant_sel ON tenants;

ALTER TABLE audit_log              NO FORCE ROW LEVEL SECURITY;
ALTER TABLE documents              NO FORCE ROW LEVEL SECURITY;
ALTER TABLE transfers              NO FORCE ROW LEVEL SECURITY;
ALTER TABLE financial_transactions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE financial_categories   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE group_attendance       NO FORCE ROW LEVEL SECURITY;
ALTER TABLE small_groups           NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ministry_members       NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ministries             NO FORCE ROW LEVEL SECURITY;
ALTER TABLE benefactors            NO FORCE ROW LEVEL SECURITY;
ALTER TABLE visitors               NO FORCE ROW LEVEL SECURITY;
ALTER TABLE member_relationships   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE families               NO FORCE ROW LEVEL SECURITY;
ALTER TABLE members                NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users                  NO FORCE ROW LEVEL SECURITY;
ALTER TABLE roles                  NO FORCE ROW LEVEL SECURITY;
ALTER TABLE branches               NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants                NO FORCE ROW LEVEL SECURITY;

ALTER TABLE audit_log              DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents              DISABLE ROW LEVEL SECURITY;
ALTER TABLE transfers              DISABLE ROW LEVEL SECURITY;
ALTER TABLE financial_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE financial_categories   DISABLE ROW LEVEL SECURITY;
ALTER TABLE group_attendance       DISABLE ROW LEVEL SECURITY;
ALTER TABLE small_groups           DISABLE ROW LEVEL SECURITY;
ALTER TABLE ministry_members       DISABLE ROW LEVEL SECURITY;
ALTER TABLE ministries             DISABLE ROW LEVEL SECURITY;
ALTER TABLE benefactors            DISABLE ROW LEVEL SECURITY;
ALTER TABLE visitors               DISABLE ROW LEVEL SECURITY;
ALTER TABLE member_relationships   DISABLE ROW LEVEL SECURITY;
ALTER TABLE families               DISABLE ROW LEVEL SECURITY;
ALTER TABLE members                DISABLE ROW LEVEL SECURITY;
ALTER TABLE users                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE roles                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches               DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenants                DISABLE ROW LEVEL SECURITY;

DROP FUNCTION IF EXISTS is_headquarters();
DROP FUNCTION IF EXISTS current_tenant();
DROP FUNCTION IF EXISTS current_branch();
